version: "3.8"

networks:
  traefik-net:
    driver: bridge

services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web9000.address=:9000"
    ports:
      - "80:80"
      - "8080:8080" # Traefik dashboard
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - traefik-net
  


  nginx:
    build: ./nginx
    container_name: nginx
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`localhost`)"
      - "traefik.http.routers.nginx.entrypoints=web"
      - "traefik.http.services.nginx.loadbalancer.server.port=80"
    volumes:
      - ../public:/usr/share/nginx/html:ro
    networks:
      - traefik-net

  
  thelounge:
    build:
      context: .
      dockerfile: thelounge.Dockerfile
    container_name: thelounge
    volumes:
      - ./thelounge-config.js:/var/opt/thelounge/config.js
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.thelounge.rule=Host(`localhost`)"
      - "traefik.http.routers.thelounge.entrypoints=web9000"
      - "traefik.http.services.thelounge.loadbalancer.server.port=9000"
    networks:
      - traefik-net


  mc:
    image: itzg/minecraft-server:java8-multiarch
    environment:
      EULA: "TRUE"
      ONLINE_MODE: "FALSE"
      VERSION: 1.12
    volumes:
      - ./server/mc:/data
    networks:
      - traefik-net

  bungeecord:
    image: itzg/bungeecord
    environment:
      TYPE: WATERFALL
      CFG_MOTD: Minecraft Eagler Server Hosted By Mirthfather
      REPLACE_ENV_VARIABLES: "true"
    volumes:
      - ./eagler-bungeecord-config.yml:/config/config.yml
      - ./server/bungee:/server
    networks:
      - traefik-net


  code-server:
    image: linuxserver/code-server:latest
    container_name: code-server
    ports:
      - "8082:8443"
    volumes:
      - ./code-workspace:/config/workspace
      - /tmp/code-server:/config/.local/share/code-server
    environment:
      - PASSWORD=student
      - DEFAULT_WORKSPACE=/config/workspace
    networks:
      - traefik-net
    restart: unless-stopped