version: "3.8"

networks:
  traefik-net:
    driver: bridge

services:
  


  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ../public:/usr/share/nginx/html:ro
    networks:
      - traefik-net

  
  thelounge:
    image: thelounge/thelounge:latest
    container_name: thelounge
    ports:
      - "9000:9000"
    volumes:
      - ./thelounge-config.js:/var/opt/thelounge/config.js
    networks:
      - traefik-net


  mc:
    image: itzg/minecraft-server:java8-multiarch
    environment:
      EULA: "TRUE"
      ONLINE_MODE: "FALSE"
      VERSION: 1.12
    volumes:
      - ./server/mc:/data
    networks:
      - traefik-net

  bungeecord:
    image: itzg/bungeecord
    ports:
      - "25577:25577"
    environment:
      TYPE: WATERFALL
      CFG_MOTD: Minecraft Eagler Server Hosted By Mirthfather
      REPLACE_ENV_VARIABLES: "true"
    volumes:
      - ./eagler-bungeecord-config.yml:/config/config.yml
      - ./server/bungee:/server
    networks:
      - traefik-net


  code-server:
    image: linuxserver/code-server:latest
    container_name: code-server
    ports:
      - "8082:8443"
    volumes:
      - ./code-workspace:/config/workspace
      - /tmp/code-server:/config/.local/share/code-server
    environment:
      - PASSWORD=student
      - DEFAULT_WORKSPACE=/config/workspace
    networks:
      - traefik-net
    restart: unless-stopped